import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";

import { WithReduxProvider } from "@/shared/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create ITECO app",
  description: "Generated by create next app & SC",
  authors: {
    name: "Ivan Mitrofanov",
    url: "https://github.com/exodie/ITECO-task",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WithReduxProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </WithReduxProvider>
      </body>
    </html>
  );
}
